In [5]:
inputs = [1,2,3]
wights = [1,1.1,2.0]
bais = 2
outputs = inputs[0] * wights[0] +  inputs[1] * wights[1] +inputs[2] * wights[2] +bais

print(outputs)



11.2


In [1]:
inputs = [1,2,3,4]
wights = [1,1.1,2.0,0.6]
bais = 2
outputs = inputs[0] * wights[0] +  inputs[1] * wights[1] +inputs[2] * wights[2]+inputs[3] * wights[3] +bais

print(outputs)

13.6


In [22]:
inputs = [1, 2.0, 3.0, 2.5]

weights = [[1, 1.1, 2.0, 0.6],
           [2, 3.0, 0.2, 0.3],
           [1, 2.0, 3.2, 2.2]]

biases = [2, 2, 2, 2]

outputs = []  # Initialize an empty list to store the results

# Calculate the outputs
for i in range(len(inputs)-1):
    output = (inputs[i] * weights[i][0] + 
              inputs[i] * weights[i][1] + 
              inputs[i] * weights[i][2] + 
              inputs[i] * weights[i][3] + 
              biases[i])
    outputs.append(output)

print(outputs)


[6.699999999999999, 13.0, 27.200000000000003]


In [19]:
inputs = [1, 2.0, 3.0, 2.5]

weights = [[1, 1.1, 2.0, 0.6],
           [2, 3.0, 0.2, 0.3],
           [1, 2.0, 3.2, 2.2]]

biases = [2, 2, 2, 2]

out_puts = []

for n_w , n_b in zip(wights,biases):
    n_output = 0
    for n_inputs , wight in zip(inputs, n_w):
        n_output = n_inputs * wight
    n_output += n_b
    out_puts.append(n_output)
    
print(out_puts)

[3.5, 2.75, 7.5]


In [2]:
inputs = [1, 2.0, 3.0, 2.5]

weights = [[1, 1.1, 2.0, 0.6],
           [2, 3.0, 0.2, 0.3],
           [1, 2.0, 3.2, 2.2]]

biases = [2, 2, 2, 2]



In [5]:
import numpy as np
inputs = [1, 2.0, 3.0, 2.5]

weights = [[1, 1.1, 2.0, 0.6],
           [2, 3.0, 0.2, 0.3],
           [1, 2.0, 3.2, 2.2]]

biases = [2, 2, 2, 2]
out_puts = np.dot(wights,inputs) + biases
print(out_puts)

[12.7 12.7 12.7 12.7]


### Creating a headen Layer 

In [9]:
import numpy as np

class layer_dense:
    def __init__(self, n_inputs, n_neural):
        self.wights = 0.10 + np.random.randn(n_inputs,n_neural)
        self.biases = np.zeros((1,n_neural))
    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.wights) + self.biases
        

        
X = [[1,2,3],
    [1,2,3]]        
layer1 = layer_dense(3,6)
layer1.forward(X)
print(layer1.outputs)


[[-4.85172323  6.85590903 -1.16295672 -0.29255075  0.60940158  1.64805086]
 [-4.85172323  6.85590903 -1.16295672 -0.29255075  0.60940158  1.64805086]]
